from fastapi import APIRouter

from app.api.v1.endpoints import (
    agents,
    canon,
    deep_agent,
    exporting,
    foreshadowing,
    knowledge,
    langsmith,
    outline_debate,
    project_studio,
    projects,
    story_bible,
    tools,
    versions,
    websockets,
    workbench,
    writing,
)

api_router = APIRouter()

api_router.add_api_route("/projects", projects.create_project, methods=["POST"])
api_router.add_api_route("/projects", project_studio.list_projects, methods=["GET"])
api_router.add_api_route("/projects/{project_id}", project_studio.get_project, methods=["GET"])
api_router.add_api_route("/projects/{project_id}", project_studio.update_project, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}", project_studio.delete_project, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/duplicate", project_studio.duplicate_project, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/state", project_studio.get_project_state, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/state", project_studio.put_project_state, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/story-bible", project_studio.get_story_bible, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/story-bible", story_bible.update_story_bible, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/story-bible/generate", project_studio.generate_story_bible, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/plan", project_studio.plan_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/book/generate", project_studio.generate_book_outline, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/book/commit", project_studio.commit_book_outline, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/chapters/batch-generate", project_studio.generate_chapter_outlines_batch, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/chapters/commit", project_studio.commit_chapter_outlines, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions", outline_debate.create_outline_debate_session, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}", outline_debate.get_outline_debate_session, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/messages", outline_debate.post_outline_debate_message, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/interrupt", outline_debate.interrupt_outline_debate_session, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/book/run", outline_debate.run_outline_debate_book, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/book/confirm", outline_debate.confirm_outline_debate_book, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/book/stream", outline_debate.stream_outline_debate_book, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/volumes/run", outline_debate.run_outline_debate_volumes, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/volumes/confirm", outline_debate.confirm_outline_debate_volumes, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/volumes/stream", outline_debate.stream_outline_debate_volumes, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/chapters/run", outline_debate.run_outline_debate_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/chapters/confirm", outline_debate.confirm_outline_debate_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/chapters/stream", outline_debate.stream_outline_debate_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/outline/debate/sessions/{session_id}/commit", outline_debate.commit_outline_debate_candidates, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters", workbench.create_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters", project_studio.list_chapters, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/chapters/reorder", workbench.reorder_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/trash", workbench.list_trash, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/chapters/trash/batch", workbench.trash_chapters, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}", project_studio.get_chapter, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}", project_studio.update_chapter, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/trash", workbench.trash_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/restore", workbench.restore_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/snapshot", workbench.snapshot_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/proposals", workbench.create_proposal, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/draft", project_studio.draft_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/rewrite", project_studio.rewrite_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/partial-rewrite", project_studio.partial_rewrite_chapter, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/chapters/{chapter_id}/chat/stream", project_studio.stream_chapter_chat, methods=["POST"])
api_router.add_api_route("/agents", agents.list_agents, methods=["GET"])
api_router.add_api_route("/llm/models", agents.list_llm_models, methods=["GET"])
api_router.add_api_route("/agent-model-configs", agents.list_agent_model_configs, methods=["GET"])
api_router.add_api_route("/agent-model-configs", agents.update_agent_model_config, methods=["PUT"])
api_router.add_api_route("/agent-model-configs/{workflow_id}/{agent_name}", agents.delete_agent_model_config, methods=["DELETE"])
api_router.add_api_route("/creation-star/options", agents.creation_star_options, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/creation-star/draw", agents.creation_star_draw, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation-star/commit", agents.creation_star_commit, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/basic-suggestions", agents.creation_basic_suggestions, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions", agents.create_creation_session, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}", agents.get_creation_session, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/worldviews", agents.creation_session_worldviews, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/protagonists", agents.creation_session_protagonists, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/market-position", agents.creation_session_market_position, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/seed", agents.creation_session_seed, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/core-conflict", agents.creation_session_core_conflict, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/constitution", agents.creation_session_constitution, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/constitution-review", agents.creation_session_constitution_review, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/canon-preview", agents.creation_session_canon_preview, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/creation/sessions/{session_id}/commit", agents.creation_session_commit, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/canon-studio/run", canon.run_canon_studio, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/canon-studio/store", canon.get_canon_studio_store, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/canon-studio/final-outline", canon.get_canon_studio_final_outline, methods=["GET"])
api_router.add_api_route("/workflows", agents.list_workflows, methods=["GET"])
api_router.add_api_route("/agents/templates", agents.create_prompt_template, methods=["POST"])
api_router.add_api_route("/agents/templates", agents.list_prompt_templates, methods=["GET"])
api_router.add_api_route("/agents/templates/import", agents.import_prompt_templates, methods=["POST"])
api_router.add_api_route("/agents/templates/export", agents.export_prompt_templates, methods=["GET"])
api_router.add_api_route("/agents/{agent_name}", agents.get_agent, methods=["GET"])
api_router.add_api_route("/agents/{agent_name}/prompt", agents.update_agent_prompt, methods=["PUT"])
api_router.add_api_route("/agents/{agent_name}/prompt/restore", agents.restore_agent_prompt, methods=["POST"])
api_router.add_api_route("/deep-agent/config", deep_agent.get_deep_agent_config, methods=["GET"])
api_router.add_api_route("/deep-agent/config", deep_agent.update_deep_agent_config, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/deep-agent/sessions", deep_agent.create_deep_agent_session, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/deep-agent/sessions", deep_agent.list_deep_agent_sessions, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/deep-agent/sessions/{session_id}", deep_agent.get_deep_agent_session, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/deep-agent/sessions/{session_id}/chat/stream", deep_agent.stream_deep_agent_chat, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/deep-agent/tool-calls/{tool_call_id}/approve", deep_agent.approve_deep_agent_tool_call, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/deep-agent/tool-calls/{tool_call_id}/reject", deep_agent.reject_deep_agent_tool_call, methods=["POST"])
api_router.add_api_route("/langsmith/status", langsmith.get_langsmith_status, methods=["GET"])
api_router.add_api_route("/langsmith/runs/{job_id}", langsmith.get_langsmith_runs, methods=["GET"])
api_router.add_api_route("/langsmith/prompts/push", langsmith.push_langsmith_prompt, methods=["POST"])
api_router.add_api_route("/langsmith/prompts/pull-preview", langsmith.pull_langsmith_prompt_preview, methods=["POST"])
api_router.add_api_route("/langsmith/evals/run", langsmith.run_langsmith_eval, methods=["POST"])
api_router.add_api_route("/write/generate", writing.write_generate, methods=["POST"])
api_router.add_api_route("/write/batch-generate", writing.batch_generate, methods=["POST"])
api_router.add_api_route("/write/pause", writing.pause_job, methods=["POST"])
api_router.add_api_route("/write/resume", writing.resume_job, methods=["POST"])
api_router.add_api_route("/write/cancel", writing.cancel_job, methods=["POST"])
api_router.add_api_route("/jobs", writing.list_jobs, methods=["GET"])
api_router.add_api_route("/jobs/{job_id}", writing.get_job, methods=["GET"])
api_router.add_api_route("/jobs/{job_id}/agent-runs", writing.get_agent_runs, methods=["GET"])
api_router.add_api_route("/jobs/{job_id}/retry", writing.retry_job, methods=["POST"])
api_router.add_api_route("/versions", versions.list_versions, methods=["GET"])
api_router.add_api_route("/versions/{chapter_id}", versions.list_chapter_versions, methods=["GET"])
api_router.add_api_route("/versions/compare", versions.compare_versions, methods=["POST"])
api_router.add_api_route("/versions/{version_id}/rollback", versions.rollback_version, methods=["POST"])
api_router.add_api_route("/versions/{version_id}/branch", versions.branch_version, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/foreshadowing", foreshadowing.list_foreshadowing, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/foreshadowing", foreshadowing.create_foreshadowing, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/foreshadowing/{item_id}", foreshadowing.update_foreshadowing, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/foreshadowing/{item_id}", foreshadowing.delete_foreshadowing, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/foreshadowing/{item_id}/payoff", foreshadowing.payoff_foreshadowing, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/characters", knowledge.list_characters, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/characters", knowledge.create_character, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/characters/{character_id}", knowledge.get_character, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/characters/{character_id}", knowledge.update_character, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/characters/{character_id}", knowledge.delete_character, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/entities", knowledge.list_entities, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/entities", knowledge.create_entity, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/entities/{entity_id}", knowledge.update_entity, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/entities/{entity_id}", knowledge.delete_entity, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/world-facts", knowledge.list_world_facts, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/world-facts", knowledge.create_world_fact, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/world-facts/{fact_id}", knowledge.update_world_fact, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/world-facts/{fact_id}", knowledge.delete_world_fact, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/settings/tree", knowledge.list_canon_tree, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/health", knowledge.get_canon_health, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/folders", knowledge.create_canon_folder, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/nodes/{node_id}/move", knowledge.move_canon_node, methods=["PATCH"])
api_router.add_api_route("/projects/{project_id}/settings/proposals", knowledge.list_canon_proposals, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/proposals/{proposal_id}/approve", knowledge.approve_canon_proposal, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/proposals/{proposal_id}/reject", knowledge.reject_canon_proposal, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/duplicates/scan", knowledge.scan_canon_duplicates, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/export", knowledge.export_canon_package, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/{ref_type}/{ref_id}/locks", knowledge.set_canon_locks, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/settings/{ref_type}/{ref_id}/impact", knowledge.get_canon_impact, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/{ref_type}/{ref_id}/versions", knowledge.list_canon_versions, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/settings/{ref_type}/{ref_id}/versions/{version_id}/rollback", knowledge.rollback_canon_version, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/archive", knowledge.archive_canon_items, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/settings/generate", knowledge.generate_settings, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/graph", knowledge.get_graph, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/graph/subgraph", knowledge.get_subgraph, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/canon/refresh", canon.refresh_canon, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/canon/context", canon.get_canon_context, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/volumes", workbench.list_volumes, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/volumes", workbench.create_volume, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/volumes/{volume_id}", workbench.update_volume, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/volumes/{volume_id}", workbench.delete_volume, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/notes", workbench.list_notes, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/notes", workbench.create_note, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/notes/{note_id}", workbench.update_note, methods=["PUT"])
api_router.add_api_route("/projects/{project_id}/notes/{note_id}", workbench.delete_note, methods=["DELETE"])
api_router.add_api_route("/projects/{project_id}/proposals", workbench.list_proposals, methods=["GET"])
api_router.add_api_route("/projects/{project_id}/proposals/{proposal_id}/apply", workbench.apply_proposal, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/proposals/{proposal_id}/reject", workbench.reject_proposal, methods=["POST"])
api_router.add_api_route("/projects/{project_id}/backup", workbench.backup_project, methods=["GET"])
api_router.add_api_route("/tools/summary", tools.summary, methods=["POST"])
api_router.add_api_route("/tools/foreshadowing", tools.foreshadowing, methods=["POST"])
api_router.add_api_route("/tools/cliffhanger", tools.cliffhanger, methods=["POST"])
api_router.add_api_route("/tools/fact-check", tools.fact_check, methods=["POST"])
api_router.add_api_route("/tools/consistency-check", tools.consistency_check, methods=["POST"])
api_router.add_api_route("/tools/learn-style", tools.learn_style, methods=["POST"])
api_router.add_api_route("/tools/query-knowledge", tools.query_knowledge, methods=["POST"])
api_router.add_api_route("/export", exporting.export_project, methods=["POST"])
api_router.add_api_route("/export/templates", exporting.export_templates, methods=["GET"])
api_router.add_api_route("/export/templates", exporting.create_export_template, methods=["POST"])
api_router.add_api_websocket_route("/ws/progress", websockets.progress_websocket)
api_router.add_api_websocket_route("/ws/jobs/{job_id}", websockets.job_websocket)
